### ISSUE TITLE
在浏览器输入链接后出现了内部服务器错误

### ISSUE THREAD

**Issue by RosyJu** [SerinaNya/SkinRenderMC#7]
当我在浏览器中输入
**http://127.0.0.1:57680/url/image/both?skinUrl=https://textures.minecraft.net/texture/32430511fb19c69bd87c9541aecfcc674ab46313f82b5d0476e65653473b41f&capeUrl=http://textures.minecraft.net/texture/cd9d82ab17fd92022dbd4a86cde4c382a7540e117fae7b9a2853658505a80625&nameTag=%22%22&definition=3&transparent=true**
时,在docker得到

---------------------------------------------------------------------------

```
2024-12-31 20:22:29 INFO:     172.17.0.1:61410 - "GET /url/image/both?skinUrl=https://textures.minecraft.net/texture/32430511fb19c69bd87c9541aecfcc674ab46313f82b5d0476e65653473b41f&capeUrl=http://textures.minecraft.net/texture/cd9d82ab17fd92022dbd4a86cde4c382a7540e117fae7b9a2853658505a80625&nameTag=%22%22&definition=3&transparent=true HTTP/1.1" 500 Internal Server Error
2024-12-31 20:22:29 ERROR:    Exception in ASGI application
2024-12-31 20:22:29 Traceback (most recent call last):
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
2024-12-31 20:22:29     result = await app(  # type: ignore[func-returns-value]
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
2024-12-31 20:22:29     return await self.app(scope, receive, send)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-12-31 20:22:29     await super().__call__(scope, receive, send)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-12-31 20:22:29     await self.middleware_stack(scope, receive, send)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-12-31 20:22:29     raise exc
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-12-31 20:22:29     await self.app(scope, receive, _send)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-12-31 20:22:29     await self.app(scope, receive, send)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-12-31 20:22:29     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-12-31 20:22:29     raise exc
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-12-31 20:22:29     await app(scope, receive, sender)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
2024-12-31 20:22:29     await self.middleware_stack(scope, receive, send)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
2024-12-31 20:22:29     await route.handle(scope, receive, send)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
2024-12-31 20:22:29     await self.app(scope, receive, send)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
2024-12-31 20:22:29     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-12-31 20:22:29     raise exc
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-12-31 20:22:29     await app(scope, receive, sender)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
2024-12-31 20:22:29     response = await func(request)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 269, in app
2024-12-31 20:22:29     solved_result = await solve_dependencies(
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 600, in solve_dependencies
2024-12-31 20:22:29     solved = await call(**sub_values)
2024-12-31 20:22:29   File "/app/server/skinview3d/core/get_image.py", line 19, in get_view
2024-12-31 20:22:29     return await get_common_response.get_both(q)
2024-12-31 20:22:29   File "/app/server/skinview3d/core/get_common_response.py", line 31, in get_both
2024-12-31 20:22:29     resp = await _get(q)
2024-12-31 20:22:29   File "/app/server/skinview3d/core/get_common_response.py", line 10, in _get
2024-12-31 20:22:29     resp = await getViewRaw(
2024-12-31 20:22:29   File "/app/server/skinview3d/render_api.py", line 28, in getViewRaw
2024-12-31 20:22:29     browser = await p.chromium.connect_over_cdp(settings.browserWSEndpoint)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 14239, in connect_over_cdp
2024-12-31 20:22:29     await self._impl_obj.connect_over_cdp(
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 172, in connect_over_cdp
2024-12-31 20:22:29     response = await self._channel.send_return_as_dict("connectOverCDP", params)
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 64, in send_return_as_dict
2024-12-31 20:22:29     return await self._connection.wrap_api_call(
2024-12-31 20:22:29   File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 513, in wrap_api_call
2024-12-31 20:22:29     raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
2024-12-31 20:22:29 playwright._impl._errors.Error: BrowserType.connect_over_cdp: WebSocket error: getaddrinfo ENOTFOUND chrome
2024-12-31 20:22:29 Call log:
2024-12-31 20:22:29 <ws connecting> ws://chrome:3000/
2024-12-31 20:22:29   - <ws error> ws://chrome:3000/ error getaddrinfo ENOTFOUND chrome
2024-12-31 20:22:29   - <ws connect error> ws://chrome:3000/ getaddrinfo ENOTFOUND chrome
2024-12-31 20:22:29   - <ws disconnected> ws://chrome:3000/ code=1006 reason=
2024-12-31 20:22:29
```
-----------------------------------------------------------------------------------

系统:Windows11
docker desktop 4.36

**Comment by SerinaNya** [comment]
看起来像是 `chrome` 容器未启动导致的

**Comment by RosyJu** [comment]
> 看起来像是 容器未启动导致的`chrome`

如何做,我还没chrome容器

**Comment by SerinaNya** [comment]
> > 看起来像是 容器未启动导致的`chrome`
> 
> 如何做,我还没chrome容器

以下是使用 `docker-compose.yml` 运行本项目的大致方法

1. 确保 Docker Desktop 运行正常
2. 保存这个文件至一个文件夹中 https://github.com/SerinaNya/SkinRenderMC/raw/master/docker-compose.yml
3. 在中这个文件夹中打开终端，运行以下命令
    ```shell
    docker compose up -d
    ```
4. 🎉 等待成功运行
    可在 Docker Desktop 内查看日志 & 管理容器

**Comment by RosyJu** [comment]
> > > 看起来像是 容器未启动导致的`chrome`
> > 
> > 
> > 如何做，我还没chrome容器
> 
> 以下是使用 运行本项目的大致方法`docker-compose.yml`
> 
> 1. 确保 Docker Desktop 运行正常
> 2. 保存这个文件至一个文件夹中 https://github.com/SerinaNya/SkinRenderMC/raw/master/docker-compose.yml
> 3. 在中这个文件夹中打开终端，运行以下命令```shell
>    docker compose up -d
>    ```
> 4. 🎉 等待成功运行
>    可在 Docker Desktop 内查看日志 & 管理容器

![image](https://github.com/user-attachments/assets/b0b2f446-0f27-439b-8598-51a28ac95ac8)
尝试使用  docker compose up -d  时似乎发生了报错
![image](https://github.com/user-attachments/assets/dec0c868-d8b4-4286-84f9-279b60bdcc47)
已经启动了容器

**Comment by SerinaNya** [comment]
> > > > 看起来像是 容器未启动导致的`chrome`
> > > 
> > > 
> > > 如何做，我还没chrome容器
> > 
> > 
> > 以下是使用 运行本项目的大致方法`docker-compose.yml`
> > 
> > 1. 确保 Docker Desktop 运行正常
> > 2. 保存这个文件至一个文件夹中 https://github.com/SerinaNya/SkinRenderMC/raw/master/docker-compose.yml
> > 3. 在中这个文件夹中打开终端，运行以下命令```shell
> >    docker compose up -d
> > 4. 🎉 等待成功运行
> >    可在 Docker Desktop 内查看日志 & 管理容器
> 
> ![image](https://private-user-images.githubusercontent.com/111301965/399480133-b0b2f446-0f27-439b-8598-51a28ac95ac8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTMzMjgsIm5iZiI6MTczNTY1MzAyOCwicGF0aCI6Ii8xMTEzMDE5NjUvMzk5NDgwMTMzLWIwYjJmNDQ2LTBmMjctNDM5Yi04NTk4LTUxYTI4YWM5NWFjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxMzUwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWRjMWMyZGE0NGViYzVmMzI3MzM3ZjUwMmE5YjExOTE3M2E1Y2YwZTUwNmEzZDEwOTk3MjVkMjNlZWNlY2YyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SMIRX_hNIbVAM_EqFIZzCp9U0QX4hvGYACBjQaZ9wmQ) 尝试使用 docker compose up -d 时似乎发生了报错 ![image](https://private-user-images.githubusercontent.com/111301965/399480463-dec0c868-d8b4-4286-84f9-279b60bdcc47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTMzMjgsIm5iZiI6MTczNTY1MzAyOCwicGF0aCI6Ii8xMTEzMDE5NjUvMzk5NDgwNDYzLWRlYzBjODY4LWQ4YjQtNDI4Ni04NGY5LTI3OWI2MGJkY2M0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxMzUwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGNiNGI3NWFjOTc4NDkyZjU1ZDVhN2I2MjUxNjk3MzE1MDNkMDExOWI1MzIzZGMwZGJmNTkzYTQ3NzE1YzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IXpG0jxBm4tmzm1GKndOq82CQRSlPmttMqej0kyLQVs) 已经启动了容器

抱歉，是我配置文件写错了，已在 https://github.com/SerinaNya/SkinRenderMC/commit/91e36acea697c31ced0a493bc417dbb6c44132a6 修正。

请重新下载 `docker-compose.yml` 后再试

**Comment by RosyJu** [comment]
> > > > > 看起来像是 容器未启动导致的`chrome`
> > > > 
> > > > 
> > > > 如何做，我还没chrome容器
> > > 
> > > 
> > > 以下是使用 运行本项目的大致方法`docker-compose.yml`
> > > 
> > > 1. 确保 Docker Desktop 运行正常
> > > 2. 保存这个文件至一个文件夹中 https://github.com/SerinaNya/SkinRenderMC/raw/master/docker-compose.yml
> > > 3. 在中这个文件夹中打开终端，运行以下命令```shell
> > >    docker compose up -d
> > > 4. 🎉 等待成功运行
> > >    可在 Docker Desktop 内查看日志 & 管理容器
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/111301965/399480133-b0b2f446-0f27-439b-8598-51a28ac95ac8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTMzMjgsIm5iZiI6MTczNTY1MzAyOCwicGF0aCI6Ii8xMTEzMDE5NjUvMzk5NDgwMTMzLWIwYjJmNDQ2LTBmMjctNDM5Yi04NTk4LTUxYTI4YWM5NWFjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxMzUwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWRjMWMyZGE0NGViYzVmMzI3MzM3ZjUwMmE5YjExOTE3M2E1Y2YwZTUwNmEzZDEwOTk3MjVkMjNlZWNlY2YyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SMIRX_hNIbVAM_EqFIZzCp9U0QX4hvGYACBjQaZ9wmQ) 尝试使用 docker compose up -d 时似乎发生了报错 ![image](https://private-user-images.githubusercontent.com/111301965/399480463-dec0c868-d8b4-4286-84f9-279b60bdcc47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTMzMjgsIm5iZiI6MTczNTY1MzAyOCwicGF0aCI6Ii8xMTEzMDE5NjUvMzk5NDgwNDYzLWRlYzBjODY4LWQ4YjQtNDI4Ni04NGY5LTI3OWI2MGJkY2M0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxMzUwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGNiNGI3NWFjOTc4NDkyZjU1ZDVhN2I2MjUxNjk3MzE1MDNkMDExOWI1MzIzZGMwZGJmNTkzYTQ3NzE1YzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IXpG0jxBm4tmzm1GKndOq82CQRSlPmttMqej0kyLQVs) 已经启动了容器
> 
> 抱歉，是我配置文件写错了，已在 [91e36ac](https://github.com/SerinaNya/SkinRenderMC/commit/91e36acea697c31ced0a493bc417dbb6c44132a6) 修正。
> 
> 请重新下载 `docker-compose.yml` 后再试

非常感谢,已经解决了,可以正常使用了
